= Setting up Angular2 CLI with Maven in enterprise network
:tags:Maven,Angular

Working with Angular2 CLI is easy - you just wait for npm to download the Internet and afterwards and then `ng` will take care of all your tooling setup.

Not so much if at your workplace you're running Windows, your network has NTLM-based firewall and your project is actually Java-based one built with Maven.

Even if the proxy for NPM can be configured via `npm set` or `http_proxy` environment variable, npm does not support `no_proxy` clause, so the things
would start failing if you want to consume your own packages.

== Needed infrastructure

Instead, we will use https://www.sonatype.com/download-oss-sonatype[Nexus 3]. We will install it on a server, that has reasonable access to Internet (e. g. no auth, or service user autorization to proxy), and it will do the proxying for all things NodeJS and NPM we need.

For running NPM as part of our Maven build, we'll use https://github.com/eirslett/frontend-maven-plugin[Frontend Maven Plugin]. It will take care of installing node, npm and project dependencies for us, and also for our CI build.

== Maven module structure

We will lay out our modules in following way:

----
parent (pom)
`- app-backend (war module)
`- app-frontend (war module)
   `- node (js project)
----

Module `app-frontend` will invoke npm build in directory `app-frontend/node`. I tried to be Maven compatible here at first, but it wasn't really helping when trying to open the JS project in the IDE. Maven will then pack the result of npm into a `.war` file. 

In case you want to deploy single artifact, `app-backend` may depend on `app-frontend` and the build result will be then copied to backend `.war`.

== Setting up proxies in Nexus



== Frontend POM
[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.example</groupId>
    <artifactId>parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <artifactId>app-frontend</artifactId>
  <packaging>war</packaging>

  <name>app-frontend</name>

  <properties>
    <!-- this is NOT a java project, therefore we do not compile anything -->
    <maven.main.skip>true</maven.main.skip>
    <maven.test.skip>true</maven.test.skip>
    <!-- this is our Nexus3 installations. No reverse proxy in front -->
    <url.nexus>http://nexus.server:8088/nexus3</url.nexus>
    <!-- proxy of https://nodejs.org/dist -->
    <node.repository>${url.nexus}/repository/node-dist/</node.repository>
    <!-- proxy of NPM registry -->
    <npm.registry>${url.nexus}/repository/npm/</npm.registry>
    <!-- location of npm installation within npm registry -->
    <npm.repository>${npm.registry}npm/-/</npm.repository>
  </properties>

  <dependencies />

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-clean-plugin</artifactId>
        <version>3.0.0</version>
        <configuration>
          <filesets>
            <fileset>
              <!-- during clean phase also clean node_modules of js project -->
              <directory>node/node_modules</directory>
            </fileset>
          </filesets>
        </configuration>
      </plugin>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
        <version>1.2</version>
        <configuration>
          <npmVersion>3.10.8</npmVersion>
          <nodeVersion>v6.9.1</nodeVersion>
          <workingDirectory>node</workingDirectory>
          <!-- node executable and npm gets installed under target/ -->
          <installDirectory>target</installDirectory>
          <npmDownloadRoot>${npm.repository}</npmDownloadRoot>
          <nodeDownloadRoot>${node.repository}</nodeDownloadRoot>
          <npmRegistryURL>${npm.registry}</npmRegistryURL>
          <npmInheritsProxyConfigFromMaven>false</npmInheritsProxyConfigFromMaven>
        </configuration>
        <executions>
          <execution>
            <!-- First, install node and npm -->
            <id>install node and npm</id>
            <goals>
              <goal>install-node-and-npm</goal>
            </goals>
            <phase>generate-resources</phase>
          </execution>
          <execution>
            <!-- And then run npm install -->
            <id>npm</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <!-- The extra arguments specify paths to proxied binaries -->
              <arguments>install --sass-binary-site=${url.nexus}/repository/node-sass/
                       --zopfli_binary_host_mirror=${url.nexus}/repository/node-zopfli</arguments>
            </configuration>
          </execution>
          <execution>
            <!-- And finally do npm run build. We do ng build --aot --prod there -->
            <id>build</id>
            <goals>
              <goal>npm</goal>
            </goals>
            <phase>prepare-package</phase>
            <configuration>
              <arguments>run build</arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>2.6</version>
        <configuration>
          <webResources>
            <!-- Put the build results and all the assets into the war -->
            <resource>
              <directory>node/dist</directory>
            </resource>
            <resource>
              <directory>node/assets</directory>
            </resource>
          </webResources>
        </configuration>
      </plugin>
    </plugins>
  </build>

</project>
----